.TH "simplesocketserver" "1" "April 2005" "" ""
.SH "NAME"
simplesocketserver \- a simple socket server for logging
.SH "SYNOPSIS"
.PP
simplesocketserver <port> <configFile>
.PP
.SH "DESCRIPTION"
.PP
simplesocketserver is part of the log4cxx C++ logging framework
and provides a simple server for centralized logging.
.PP
.SH "OPTIONS"
.PP
The following parameters are required to run simplesocketserver:
.PP
.IP "\fB<port>\fP" 
The TCP port on which to listen for logging requests.
.IP "\fB<configFile>\fP" 
The configuration file for simplesocketserver. This file is used
to configure the appenders to which logging requests are sent. The
format is the same as the usual property file which is used 
to configure log4cxx.
.PP 
.SH "AUTHOR" 
.PP 
The log4cxx framework was written by Michael Catanzariti and
Edmond Nolan.
